name: werewolfjudge
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+5

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: 0.15.1
  firebase_core: ^0.5.0
  apple_sign_in: ^0.1.0
  font_awesome_flutter: 8.8.1
  firebase_auth: 0.18.0+1
  google_sign_in: 4.5.1
  cloud_firestore: 0.14.0+1
  shared_preferences: 0.5.8
  pin_code_fields: 4.0.0
  wakelock: 0.1.4+2
  rxdart: 0.24.1
  url_launcher: 5.5.0
  flutter_signin_button: 1.0.0
  image_cropper: 1.2.3
  firebase_storage: 4.0.0
  path_provider: 1.6.11
  image_picker: 0.6.7+4
  transparent_image: 1.0.0
  vibration: 1.4.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/audio_end/celebrity.m4a
    - assets/audio_end/gargoyle.m4a
    - assets/audio_end/guard.m4a
    - assets/audio_end/hunter.m4a
    - assets/audio_end/magician.m4a
    - assets/audio_end/moderator.m4a
    - assets/audio_end/nightmare.m4a
    - assets/audio_end/psychic.m4a
    - assets/audio_end/seer.m4a
    - assets/audio_end/witch.m4a
    - assets/audio_end/wolf.m4a
    - assets/audio_end/wolf_king.m4a
    - assets/audio_end/wolf_queen.m4a
    - assets/audio_end/wolf_robot.m4a
    - assets/audio_end/wolf_brother.m4a
    - assets/audio_end/black_trader.m4a
    - assets/audio_end/slacker.m4a
    - assets/audio/celebrity.m4a
    - assets/audio/gargoyle.m4a
    - assets/audio/guard.m4a
    - assets/audio/hunter.m4a
    - assets/audio/magician.m4a
    - assets/audio/moderator.m4a
    - assets/audio/night.m4a
    - assets/audio/night_end.m4a
    - assets/audio/nightmare.m4a
    - assets/audio/psychic.m4a
    - assets/audio/seer.m4a
    - assets/audio/witch.m4a
    - assets/audio/wolf.m4a
    - assets/audio/wolf_king.m4a
    - assets/audio/wolf_queen.m4a
    - assets/audio/wolf_robot.m4a
    - assets/audio/black_trader.m4a
    - assets/audio/wolf_brother.m4a
    - assets/audio/lucky_son.m4a
    - assets/audio/slacker.m4a
    - assets/images/blood_moon.png
    - assets/images/celebrity.png
    - assets/images/cupid.png
    - assets/images/moderator.png
    - assets/images/gargoyle.png
    - assets/images/graveyard_keeper.png
    - assets/images/guard.png
    - assets/images/hidden_wolf.png
    - assets/images/hunter.png
    - assets/images/idiot.png
    - assets/images/knight.png
    - assets/images/wolf_seeder.png
    - assets/images/magician.png
    - assets/images/nightmare.png
    - assets/images/pervert.png
    - assets/images/seer.png
    - assets/images/slacker.png
    - assets/images/thief.png
    - assets/images/villager.png
    - assets/images/witch.png
    - assets/images/witcher.png
    - assets/images/wolf.png
    - assets/images/wolf_king.png
    - assets/images/wolf_queen.png
    - assets/images/black_trader.png
    - assets/app_icon.png

  fonts:
    - family: Brands
      fonts:
        - asset: assets/fonts/brands.otf
    - family: Duo
      fonts:
        - asset: assets/fonts/duo.otf
    - family: Regular
      fonts:
        - asset: assets/fonts/regular.otf
    - family: Solid
      fonts:
        - asset: assets/fonts/solid.otf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
